// ═══════════════════════════════════════════════════════════════════
// site.config.js — HES Consultancy International
// Dit is het ENIGE bestand dat je aanpast voor content wijzigingen.
// ═══════════════════════════════════════════════════════════════════
window.SITE = {
  // ── MERK & CONTACT ──────────────────────────────────────────────
  brand: {
    name:        'HES Consultancy International',
    tagline:     'European GTM Partner — From Strategy to First Customer',
    domain:      'hes-consultancy.nl',
    intDomain:   'hes-consultancy-international.com',
    email:       'mbhes@hes-consultancy-international.com',
    phone:       '+31 6 XX XX XX XX',
    phoneDisplay:'+31 6 XX XX XX XX',
    calendly:    'https://calendly.com/mbhes1970/30min',
    logo_white:  '/White_logo_-_no_background.png',
    logo_color:  '/Color_logo_-_no_background.png',
    mike_photo:  '/Mike_Hes_Foto.jpg',
  },
  // ── INTEGRATIES ──────────────────────────────────────────────────
  integrations: {
    pocketbase:   'https://api.hes-consultancy-international.com',
    slack_proxy:  '/api/slack',
    quickscan:    '/hci-quickscan.html',
    cmofmo:       '/hci-cmofmo.html',
  },
  // ── NAVIGATIE ────────────────────────────────────────────────────
  nav: {
    links: [
      { label_nl: 'Home',         label_en: 'Home',          href: '/' },
      { label_nl: 'Methodiek',    label_en: 'Methodology',   href: '/methodologie' },
      { label_nl: 'Mike Hes',     label_en: 'Mike Hes',      href: '/mike' },
      { label_nl: 'Insights',     label_en: 'Insights',      href: '/insights.html' },
    ],
    cta_nl: 'Gesprek plannen',
    cta_en: 'Schedule a call',
    cta_href: 'https://calendly.com/mbhes1970/30min',
  },
  // ── HOMEPAGE ─────────────────────────────────────────────────────
  home: {
    hero_overline_nl: 'HES Consultancy International — 30 jaar C-level ervaring',
    hero_overline_en: 'HES Consultancy International — 30 years C-level experience',
    hero_h1_nl:   'Tech bedrijven falen niet<br>door een slecht product.<br><em>Ze falen door de verkeerde volgorde.</em>',
    hero_h1_en:   'Tech companies don\'t fail<br>because of a bad product.<br><em>They fail because of the wrong sequence.</em>',
    hero_sub_nl:  'Of u nu Europa wilt betreden, uw pipeline wilt vullen, of compliant wilt worden — wij beginnen altijd op dezelfde plek: de waarheid.',
    hero_sub_en:  'Whether you want to enter Europe, fill your pipeline, or become compliant — we always start in the same place: the truth.',
    hero_cta_nl:  'Kies uw route →',
    hero_cta_en:  'Choose your route →',
    hero_cta_href: '#routes',
    hero_ghost_nl: 'Hoe het werkt',
    hero_ghost_en: 'How it works',
    hero_ghost_href: '#method',
    stats: [
      { num: '30+', label_nl: 'Jaar C-level ervaring\nBenelux & DACH', label_en: 'Years C-level experience\nBenelux & DACH' },
      { num: '4',   label_nl: 'EU-regelgevingen\nNIS2 · CRA · DORA · AI Act', label_en: 'EU regulations\nNIS2 · CRA · DORA · AI Act' },
      { num: '12w', label_nl: 'Van propositie naar\neerste klant', label_en: 'From proposition to\nfirst customer' },
    ],
    method_eyebrow_nl: 'Methodiek',
    method_eyebrow_en: 'Methodology',
    method_title_nl:   'Vier stappen. <em>Geen ruis.</em>',
    method_title_en:   'Four steps. <em>No noise.</em>',
    method_sub_nl:     'Elk traject begint met een gratis assessment. Geen verplichtingen, geen verrassingen.',
    method_sub_en:     'Every engagement starts with a free assessment. No obligations, no surprises.',
    method_steps: [
      { num: '01', title_nl: 'Quickscan', title_en: 'Quickscan', desc_nl: 'Gratis digitale assessment. In 7 minuten weet u waar u staat.', desc_en: 'Free digital assessment. In 7 minutes you know where you stand.' },
      { num: '02', title_nl: 'Analyse', title_en: 'Analysis', desc_nl: 'AI-gestuurde gap-analyse op uw specifieke situatie en sector.', desc_en: 'AI-driven gap analysis for your specific situation and sector.' },
      { num: '03', title_nl: 'Plan', title_en: 'Plan', desc_nl: 'CMO→FMO routekaart met concrete milestones en KPI\'s.', desc_en: 'CMO→FMO roadmap with concrete milestones and KPIs.' },
      { num: '04', title_nl: 'Executie', title_en: 'Execution', desc_nl: 'Begeleiding van strategie naar eerste resultaat. Hands-on.', desc_en: 'Guidance from strategy to first result. Hands-on.' },
    ],
    method_tagline_nl: 'De juiste volgorde afdwingen maakt het verschil tussen <strong>maanden aanmodderen</strong> en <strong>12 weken naar eerste klant</strong>.',
    method_tagline_en: 'Enforcing the right sequence makes the difference between <strong>months of struggle</strong> and <strong>first customer in 12 weeks</strong>.',
  },
  // ── ICP DEFINITIES ───────────────────────────────────────────────
  icps: {
    icp1: {
      id:           'icp1',
      route:        '/icp1-eu-entry.html',
      utm_icp:      'icp1',
      accent:       '#6C5CE7',
      accent_dim:   'rgba(108,92,231,.12)',
      icon:         '🚀',
      label_nl:     'Tech / ISV / Startup',
      label_en:     'Tech / ISV / Startup',
      kicker_nl:    'EU Market Entry',
      kicker_en:    'EU Market Entry',
      hero_h1_nl:   'Uw software product klaar voor <em>de Europese markt.</em>',
      hero_h1_en:   'Your software product ready for <em>the European market.</em>',
      hero_sub_nl:  'HCI begeleidt tech-bedrijven van product-market fit naar eerste Europese klanten. Strategie, GTM en uitvoering in één aanpak.',
      hero_sub_en:  'HCI guides tech companies from product-market fit to first European customers. Strategy, GTM and execution in one approach.',
      chips_nl:     ['EU Market Entry strategie', 'Partner & reseller netwerk', 'NIS2 / GDPR compliance ready', 'Van strategie naar eerste klant'],
      chips_en:     ['EU Market Entry strategy', 'Partner & reseller network', 'NIS2 / GDPR compliance ready', 'From strategy to first customer'],
      problem_nl:   ['Verkeerde volgorde — product pushen zonder market fit', 'Compliance onbekend — NIS2, CRA, GDPR niet op orde', 'Geen netwerk — EU enterprise sales vereist lokale partners'],
      problem_en:   ['Wrong sequence — pushing product without market fit', 'Compliance unknown — NIS2, CRA, GDPR not in order', 'No network — EU enterprise sales requires local partners'],
      steps_nl:     [
        { title: 'PMC Assessment', desc: 'Product-Market-Compliance fit analyse voor uw specifieke sector.' },
        { title: 'GTM Strategie', desc: 'Go-to-market plan met partner netwerk, pricing en positioning.' },
        { title: 'Eerste Klant', desc: 'Hands-on begeleiding tot de eerste getekende deal.' },
      ],
      steps_en:     [
        { title: 'PMC Assessment', desc: 'Product-Market-Compliance fit analysis for your specific sector.' },
        { title: 'GTM Strategy', desc: 'Go-to-market plan with partner network, pricing and positioning.' },
        { title: 'First Customer', desc: 'Hands-on guidance to the first signed deal.' },
      ],
      cta_nl:       'Doe de EU Readiness Assessment →',
      cta_en:       'Take the EU Readiness Assessment →',
      cta_href:     '/hci-quickscan.html?icp=icp1',
      secondary_nl: 'Of bekijk de methodiek →',
      secondary_en: 'Or view the methodology →',
      secondary_href: '/#method',
    },
    icp2: {
      id:           'icp2',
      route:        '/icp2-growth.html',
      utm_icp:      'icp2',
      accent:       '#0891b2',
      accent_dim:   'rgba(8,145,178,.12)',
      icon:         '🤝',
      label_nl:     'Partner / Reseller',
      label_en:     'Partner / Reseller',
      kicker_nl:    'Pipeline Growth',
      kicker_en:    'Pipeline Growth',
      hero_h1_nl:   'Word HCI partner en verdien aan <em>compliance & AI projecten.</em>',
      hero_h1_en:   'Become an HCI partner and earn on <em>compliance & AI projects.</em>',
      hero_sub_nl:  'HCI biedt structureel partnerschap: white-label diensten, deal registratie en gezamenlijke enterprise verkoop.',
      hero_sub_en:  'HCI offers structural partnership: white-label services, deal registration and joint enterprise sales.',
      chips_nl:     ['White-label diensten', 'Deal registratie & bescherming', 'Gezamenlijke enterprise sales', 'Partner playbook & enablement'],
      chips_en:     ['White-label services', 'Deal registration & protection', 'Joint enterprise sales', 'Partner playbook & enablement'],
      benefits_nl:  [
        { title: 'White-Label Diensten', desc: 'Lever HCI compliance & AI diensten onder uw eigen merk aan uw klanten.' },
        { title: 'Deal Registratie', desc: 'Bescherm uw leads met transparante deal registratie en margin garantie.' },
        { title: 'Joint Sales', desc: 'Gezamenlijke enterprise presentaties met HCI expertise op de achtergrond.' },
        { title: 'Enablement', desc: 'Partner playbook, sales training en technische certificering.' },
      ],
      benefits_en:  [
        { title: 'White-Label Services', desc: 'Deliver HCI compliance & AI services under your own brand to your clients.' },
        { title: 'Deal Registration', desc: 'Protect your leads with transparent deal registration and margin guarantee.' },
        { title: 'Joint Sales', desc: 'Joint enterprise presentations with HCI expertise in the background.' },
        { title: 'Enablement', desc: 'Partner playbook, sales training and technical certification.' },
      ],
      journey_nl:   [
        { title: 'Gesprek', desc: 'Kennismaking en alignment op doelen en marktsegment.' },
        { title: 'Onboarding', desc: 'Partner playbook, tools en eerste gezamenlijke case.' },
        { title: 'Eerste Deal', desc: 'Gezamenlijke pipeline opbouw en eerste gesloten deal.' },
      ],
      journey_en:   [
        { title: 'Conversation', desc: 'Introduction and alignment on goals and market segment.' },
        { title: 'Onboarding', desc: 'Partner playbook, tools and first joint case.' },
        { title: 'First Deal', desc: 'Joint pipeline building and first closed deal.' },
      ],
      cta_nl:       'Plan een partnergesprek →',
      cta_en:       'Schedule a partner call →',
      cta_href:     'https://calendly.com/mbhes1970/30min',
      secondary_nl: 'Bekijk partner voordelen →',
      secondary_en: 'View partner benefits →',
      secondary_href: '#benefits',
    },
    icp3: {
      id:           'icp3',
      route:        '/icp3-compliance.html',
      utm_icp:      'icp3',
      accent:       '#1e3a5f',
      accent_dim:   'rgba(30,58,95,.15)',
      icon:         '🏛️',
      label_nl:     'Compliance Eindklant',
      label_en:     'Compliance End Customer',
      kicker_nl:    'NIS2 · BIO · AVG · AI Act · DORA · CRA',
      kicker_en:    'NIS2 · BIO · GDPR · AI Act · DORA · CRA',
      hero_h1_nl:   'EU-regelgeving als <em>concurrentievoordeel.</em>',
      hero_h1_en:   'EU regulation as a <em>competitive advantage.</em>',
      hero_sub_nl:  'HCI helpt organisaties navigeren door complexe Europese regelgeving. Van nulmeting tot implementatie — sector-specifiek.',
      hero_sub_en:  'HCI helps organisations navigate complex European regulations. From baseline assessment to implementation — sector-specific.',
      hero_stats:   [
        { num: '8', label_nl: 'Sectoren', label_en: 'Sectors' },
        { num: '6+', label_nl: 'EU frameworks', label_en: 'EU frameworks' },
        { num: '7 min', label_nl: 'Gratis quickscan', label_en: 'Free quickscan' },
      ],
      how_it_works_nl: [
        { num: '01', title: 'Quickscan', desc: 'Gratis digitale assessment in 7 minuten. Direct inzicht in uw compliance status.' },
        { num: '02', title: 'AI Rapport', desc: 'Geautomatiseerde gap-analyse met concrete aanbevelingen per framework.' },
        { num: '03', title: 'HCI Begeleiding', desc: 'Expert begeleiding van nulmeting tot volledige implementatie.' },
      ],
      how_it_works_en: [
        { num: '01', title: 'Quickscan', desc: 'Free digital assessment in 7 minutes. Instant insight into your compliance status.' },
        { num: '02', title: 'AI Report', desc: 'Automated gap analysis with concrete recommendations per framework.' },
        { num: '03', title: 'HCI Guidance', desc: 'Expert guidance from baseline assessment to full implementation.' },
      ],
      cta_nl:       'Doe de gratis Quickscan →',
      cta_en:       'Take the free Quickscan →',
      cta_href:     '/hci-quickscan.html',
      secondary_nl: 'Kies uw sector →',
      secondary_en: 'Choose your sector →',
      secondary_href: '#sectoren',
    },
  },
  // ── SECTOREN (ICP3) ──────────────────────────────────────────────
  // Nieuwe sector toevoegen: kopieer één blok, pas aan. Klaar.
  sectors: [
    {
      id: 's01', icon: '🏛️',
      color: '#1e3a5f', accent: '#60a5fa',
      label_nl: 'Gemeente & Overheid',
      label_en: 'Government & Public Sector',
      sub_nl:   'Gemeenten · Provincies · Waterschappen · ZBO\'s',
      sub_en:   'Municipalities · Provinces · Government bodies',
      frameworks: ['BIO', 'NIS2', 'AVG', 'AI Act'],
      pain_nl:  ['BIO-verplichtingen niet geïmplementeerd', 'NIS2 meldplicht onduidelijk', 'AI Act risico-classificatie onbekend', 'Geen DPIA-proces ingericht'],
      pain_en:  ['BIO obligations not yet implemented', 'NIS2 reporting obligation unclear', 'AI Act risk classification unknown', 'No DPIA process in place'],
      cta_href: '/hci-quickscan.html?sector=s01',
    },
    {
      id: 's02', icon: '🏥',
      color: '#065f46', accent: '#4ade80',
      label_nl: 'Ziekenhuis & Zorg',
      label_en: 'Healthcare',
      sub_nl:   'Ziekenhuizen · GGZ · Huisartsen · ZBC\'s',
      sub_en:   'Hospitals · Mental Health · GP practices',
      frameworks: ['NEN 7510', 'NIS2', 'AVG', 'MDR'],
      pain_nl:  ['Patiëntdata kwetsbaar bij ransomware', 'NIS2 geldt voor zorginstellingen', 'Medische AI niet gecertificeerd', 'Datalekken niet binnen 72 uur gemeld'],
      pain_en:  ['Patient data vulnerable to ransomware', 'NIS2 applies to healthcare', 'Medical AI tools not certified', 'Data breaches not reported within 72h'],
      cta_href: '/hci-quickscan.html?sector=s02',
    },
    {
      id: 's03', icon: '💻',
      color: '#6C5CE7', accent: '#a78bfa',
      label_nl: 'Software & Developers',
      label_en: 'Software & Developers',
      sub_nl:   'SaaS · Platform · Managed Services 10-250 FTE',
      sub_en:   'SaaS · Platform · Managed Services 10-250 FTE',
      frameworks: ['CRA', 'AI Act', 'ISO 27001', 'NIS2'],
      pain_nl:  ['CE-markering CRA verplicht per 2027', 'AI features vallen onder hoog-risico', 'ISO 27001 certificering ontbreekt', 'SBOM lifecycle niet ingericht'],
      pain_en:  ['CE marking CRA mandatory by 2027', 'AI features fall under high risk', 'ISO 27001 certification missing', 'SBOM lifecycle not in place'],
      cta_href: '/hci-quickscan.html?sector=s03',
    },
    {
      id: 's04', icon: '🏦',
      color: '#7f1d1d', accent: '#f87171',
      label_nl: 'Finance & Banking',
      label_en: 'Finance & Banking',
      sub_nl:   'Banken · Verzekeraars · FinTech · Pensioenen',
      sub_en:   'Banks · Insurers · FinTech · Pensions',
      frameworks: ['DORA', 'PSD2', 'NIS2', 'AI Act'],
      pain_nl:  ['DORA operationele weerbaarheid verplicht', 'ICT third-party risico onduidelijk', 'AI credit scoring hoog-risico AI Act', 'Incident response niet getest'],
      pain_en:  ['DORA operational resilience mandatory', 'ICT third-party risk unclear', 'AI credit scoring high-risk AI Act', 'Incident response not tested'],
      cta_href: '/hci-quickscan.html?sector=s04',
    },
    {
      id: 's05', icon: '⚡',
      color: '#78350f', accent: '#fbbf24',
      label_nl: 'Energie & Utilities',
      label_en: 'Energy & Utilities',
      sub_nl:   'Energie · Water · Afval · Kritieke Infra',
      sub_en:   'Energy · Water · Waste · Critical Infrastructure',
      frameworks: ['NIS2', 'CER', 'AVG', 'AI Act'],
      pain_nl:  ['Kritieke infra — hoogste NIS2 klasse', 'OT/IT convergentie nieuwe aanvallen', 'Leveranciersrisico in energieketen', 'Real-time monitoring door toezichthouder'],
      pain_en:  ['Critical infra — highest NIS2 class', 'OT/IT convergence new attack surface', 'Supplier risk in energy chain', 'Real-time monitoring required'],
      cta_href: '/hci-quickscan.html?sector=s05',
    },
    {
      id: 's06', icon: '📡',
      color: '#134e4a', accent: '#2dd4bf',
      label_nl: 'Telecom & Kritieke Infra',
      label_en: 'Telecom & Critical Infrastructure',
      sub_nl:   'Telecomoperators · ISP\'s · Datacenters',
      sub_en:   'Telecom operators · ISPs · Datacenters',
      frameworks: ['NIS2', 'EECC', 'Telecomwet', 'CER'],
      pain_nl:  ['NIS2+EECC dubbel regime verplicht', 'OT/SCADA legacy beveiliging', '5G Toolbox niet geïmplementeerd', 'Post-quantum migratie deadline 2030'],
      pain_en:  ['NIS2+EECC dual regime mandatory', 'OT/SCADA legacy security', '5G Toolbox not implemented', 'Post-quantum migration deadline 2030'],
      cta_href: '/hci-quickscan.html?sector=s06',
    },
    {
      id: 's07', icon: '🚛',
      color: '#1d4ed8', accent: '#3b82f6',
      label_nl: 'Logistiek & Supply Chain',
      label_en: 'Logistics & Supply Chain',
      sub_nl:   'Transport · Warehousing · Douane · Distributie',
      sub_en:   'Transport · Warehousing · Customs · Distribution',
      frameworks: ['NIS2', 'eFTI', 'AVG'],
      pain_nl:  ['NIS2 kritieke infrastructuur classificatie', 'eFTI elektronische vrachtdocumentatie verplicht', 'Cybersecurity in supply chain kwetsbaar', 'AI-adoptie in warehouse zonder governance'],
      pain_en:  ['NIS2 critical infrastructure classification', 'eFTI electronic freight documentation mandatory', 'Cybersecurity in supply chain vulnerable', 'AI adoption in warehouse without governance'],
      cta_href: '/hci-quickscan.html?sector=s07',
    },
    {
      id: 's08', icon: '\u2696\uFE0F',
      color: '#047857', accent: '#10b981',
      label_nl: 'Legal & LegalTech',
      label_en: 'Legal & LegalTech',
      sub_nl:   'Advocatuur · Notariaat · Legal Ops · Contract Automation',
      sub_en:   'Law Firms · Notaries · Legal Ops · Contract Automation',
      frameworks: ['AI Act', 'NIS2', 'DORA', 'AVG'],
      pain_nl:  ['AI Act Article 6: juridisch advies-AI = hoog risico', 'NIS2 indirect in scope via kritieke sector klanten', 'DORA voor legal teams in financiële sector', 'AVG en beroepsgeheim spanning bij AI-tools'],
      pain_en:  ['AI Act Article 6: legal advice AI = high risk', 'NIS2 indirectly in scope via critical sector clients', 'DORA for legal teams in financial sector', 'GDPR and professional secrecy tension with AI tools'],
      cta_href: '/hci-quickscan.html?sector=s08',
    },
    // TEMPLATE: Nieuwe sector toevoegen — kopieer dit blok:
    // {
    //   id: 's07', icon: '🎓',
    //   color: '#1a4731', accent: '#34d399',
    //   label_nl: 'Onderwijs',
    //   label_en: 'Education',
    //   sub_nl:   'Universiteiten · Hogescholen · MBO',
    //   sub_en:   'Universities · Colleges · Vocational',
    //   frameworks: ['AVG', 'BIO-light', 'NIS2'],
    //   pain_nl:  ['...'],
    //   pain_en:  ['...'],
    //   cta_href: '/hci-quickscan.html?sector=s07',
    // },
  ],
  // ── MIKE HES ─────────────────────────────────────────────────────
  mike: {
    name:       'Mike Hes',
    title_nl:   'Trusted Advisor CxO\'s',
    title_en:   'Trusted Advisor CxO\'s',
    phone:      '+31 6 14756834',
    linkedin:   'https://linkedin.com/in/mihes/',
    calendly:   'https://calendly.com/mbhes1970/30min',
    years:      '30+',
    years_label_nl: 'Jaar C-level\nervaring EU',
    years_label_en: 'Years C-level\nexperience EU',
    bio_nl: [
      '30 jaar geleden begon ik als een van de eerste Europese medewerkers bij Citrix. Daarna Huawei, DXC/Dedalus, Login Consultants, Telindus. Ik heb gezien wat werkt in enterprise sales, en wat niet meer werkt.',
      'Koude acquisitie heeft een conversieratio van 2%. Mensen lezen geen mails, pakken de telefoon niet op. Dat is geen tijdelijk probleem, het is structureel.',
      'HCI is mijn antwoord. Een methodologie gebaseerd op 30 jaar praktijk, met AI-tools die de klant zichzelf laten kwalificeren voordat er een gesprek plaatsvindt.',
    ],
    bio_en: [
      '30 years ago I joined Citrix as one of the first European employees. Then Huawei, DXC/Dedalus, Login Consultants, Telindus. I have seen what works in enterprise sales, and what no longer does.',
      'Cold outreach has a 2% conversion rate. People don\'t read emails, don\'t answer the phone. That is not a temporary problem, it is structural.',
      'HCI is my answer. A methodology built on 30 years of practice, with AI tools that let the customer qualify themselves before a single conversation takes place.',
    ],
    bio_short_nl: 'Ik ben Mike Hes. 30 jaar C-level ervaring in EU tech & compliance. Ik heb gezien wat werkt — en wat niet. De meeste bedrijven maken dezelfde fouten. De juiste volgorde afdwingen maakt het verschil tussen maanden aanmodderen en binnen 12 weken de eerste klant.',
    bio_short_en: 'I am Mike Hes. 30 years C-level experience in EU tech & compliance. I\'ve seen what works — and what doesn\'t. Most companies make the same mistakes. Enforcing the right order makes the difference between months of struggle and the first customer within 12 weeks.',
    cta_nl:     'Plan een gesprek →',
    cta_en:     'Schedule a call →',
    stats: [
      { value: '30+', label_nl: 'jaar ICT ervaring', label_en: 'years ICT experience' },
      { value: '300%', label_nl: 'groei YoY (Huawei)', label_en: 'growth YoY (Huawei)' },
      { value: '\u20AC80M+', label_nl: 'omzet aangestuurd', label_en: 'revenue managed' },
      { value: '6', label_nl: 'sectoren, 1 methodologie', label_en: 'sectors, 1 methodology' },
    ],
    career_track: [
      'Vobis Microcomputers',
      'Citrix Systems',
      'PQR',
      'eSeSix Computer',
      'NEH ICT Solutions',
      'Telindus (Proximus)',
      'Login Consultants / Orange Business Services',
      'Huawei Technologies',
      'DXC Technologies / Dedalus',
      'EPAM Systems',
      'Atomic Group (Uniserver)',
      'Open Health Hub',
      'First Line Software',
      'HCI / Nxt Era Solutions',
    ],
    client_track: [
      {
        sector: 'Finance & Banking',
        sector_en: 'Finance & Banking',
        clients: ['ABN AMRO', 'Rabobank', 'De Nederlandsche Bank', 'KPMG', 'VUmc', 'AMC'],
      },
      {
        sector: 'Healthcare & Pharma',
        sector_en: 'Healthcare & Pharma',
        clients: ['Philips', 'Medtronic', 'DSM', 'J&J', 'Bayer', 'Novartis', 'Dr\u00E4ger', 'Siemens Health', 'Sectra', 'VZVZ', 'MedMij', 'Min. VWS', 'Catharina Ziekenhuis'],
      },
      {
        sector: 'DACH Enterprise',
        sector_en: 'DACH Enterprise',
        clients: ['Deutsche Telekom Health', 'Siemens Health', 'Dr\u00E4ger', 'T-Systems', 'Deutsche Bank'],
      },
      {
        sector: 'Technology & Telecom',
        sector_en: 'Technology & Telecom',
        clients: ['KPN', 'T-Mobile', 'Canon', 'Ziggo', 'ASML'],
      },
      {
        sector: 'Logistics & Industrie',
        sector_en: 'Logistics & Industry',
        clients: ['PostNL', 'DHL', 'DPD', 'Mammoet', 'IKEA', 'Vitens'],
      },
    ],
  },
  // ── RESULTATEN / PROOF ───────────────────────────────────────────
  proof: [
    {
      client:  'Chunk Works',
      icp:     'icp1',
      result_nl: 'CMO→FMO templates gebouwd, 6 sectoren. Werkend assessment platform. Concept naar productie in 12 weken.',
      result_en: 'Built 6 sector CMO→FMO templates. Live assessment platform. Concept to production in 12 weeks.',
    },
    {
      client:  'ElanWave',
      icp:     'icp1',
      result_nl: 'EU Market Entry strategie gedefinieerd. Eerste 3 enterprise leads gegenereerd.',
      result_en: 'EU Market Entry strategy defined. First 3 enterprise leads generated.',
    },
    {
      client:  'Health IQ Plus',
      icp:     'icp3',
      result_nl: 'NIS2 gap-analyse voltooid. Implementatieplan voor 4 maanden opgeleverd.',
      result_en: 'NIS2 gap analysis completed. 4-month implementation plan delivered.',
    },
  ],
  // ── CASES ───────────────────────────────────────────────────────
  cases: [
    {
      id: 'chunkworks',
      company: 'Chunk Works',
      tag: 'Post-quantum security \u00B7 TNO spin-off',
      status: 'active',
      text_nl: 'ChunkWorks, een TNO spin-off met post-quantum encryptie technologie, had een sterk product maar geen Europese go-to-market strategie. Mike Hes stapte in als Global VP Sales en implementeerde de volledige HCI Methodologie: van Partner Enablement (Convince, Onboard, Certify) tot CMO-FMO rapporten en sector-specifieke playbooks. Resultaat: een actief partner netwerk met Protinus IT, IT2Growth, BlueNap, Idaita en Datasur, gepositioneerd voor NIS2 en NEN7510 compliance markten.',
      text_en: 'ChunkWorks, a TNO spin-off with post-quantum encryption technology, had a strong product but no European go-to-market strategy. Mike Hes joined as Global VP Sales and implemented the full HCI Methodology: from Partner Enablement (Convince, Onboard, Certify) to CMO-FMO reports and sector-specific playbooks. Result: an active partner network with Protinus IT, IT2Growth, BlueNap, Idaita and Datasur, positioned for NIS2 and NEN7510 compliance markets.',
      results: ['5 actieve partners', 'NIS2 + NEN7510 positionering', 'Convince-Onboard-Certify'],
      icp: 'icp1',
    },
    {
      id: 'openhealthhub',
      company: 'Open Health Hub',
      tag: 'Healthcare \u00B7 FHIR \u00B7 Product strategie',
      status: 'previous',
      text_nl: 'Open Health Hub had een platform dat al bestond in een competitieve markt. Intern werd het als baanbrekend gezien, maar de markt was al volwassen. Na een assessment zag Mike een product dat de CTO had ontworpen maar nooit had geprioriteerd: een FHIR viewer en builder die wel onderscheidend was. Advies: stop met het commodityproduct, zet alles op het nieuwe product. De FHIR viewer is sindsdien naar de markt gebracht en vormt nu de kern van de oplossing.',
      text_en: 'Open Health Hub had a platform that already existed in a competitive market. Internally it was seen as groundbreaking, but the market was already mature. After an assessment Mike identified a product the CTO had designed but never prioritized: a FHIR viewer and builder that was genuinely distinctive. Advice: stop with the commodity product, focus everything on the new one. The FHIR viewer has since been brought to market and now forms the core of the solution.',
      results: ['FHIR viewer naar markt', 'Product focus shift', 'HCI Assessment toegepast'],
      icp: 'icp1',
    },
    {
      id: 'elanwave',
      company: 'ElanWave',
      tag: 'Software engineering \u00B7 Microsoft Partner \u00B7 Transformatie',
      status: 'active',
      text_nl: 'ElanWave is een Microsoft-gecertificeerd software engineering bedrijf dat de overstap wil maken van projectgedreven staffing naar een structureel dienstenaanbod. Mike Hes begeleidt dat verandertraject: GTM strategie, outreach model en commerci\u00EBle positionering opgebouwd vanuit de HCI Methodologie.',
      text_en: 'ElanWave is a Microsoft-certified software engineering company making the transition from project-driven staffing to a structural service offering. Mike Hes guides that change process: GTM strategy, outreach model and commercial positioning built on the HCI Methodology.',
      results: ['GTM strategie', 'HCI Methodologie', 'Verandertraject'],
      icp: 'icp1',
    },
    {
      id: 'atomic',
      company: 'Atomic Group (Uniserver)',
      tag: 'Hybrid Cloud \u00B7 Enterprise \u00B7 Sovereign AI',
      status: 'previous',
      text_nl: 'Bij Atomic/Uniserver bouwde Mike Hes een nieuwe Business Unit op rond Hybrid Cloud en AI/Data Analytics. Nieuwe enterprise klanten waaronder KNAB Bank en SHV/KIWA werden onboarded. Sovereign cloud gepositioneerd voor NIS2, DORA, EUCS en AI Act.',
      text_en: 'At Atomic/Uniserver Mike Hes built a new Business Unit around Hybrid Cloud and AI/Data Analytics. New enterprise clients including KNAB Bank and SHV/KIWA were onboarded. Sovereign cloud positioned for NIS2, DORA, EUCS and AI Act.',
      results: ['KNAB Bank onboarded', 'SHV/KIWA onboarded', 'NIS2 + DORA + EUCS'],
      icp: 'icp3',
    },
  ],
  // ── METHODOLOGIE ────────────────────────────────────────────────
  methodology: {
    title_nl: 'De HCI Methodologie',
    title_en: 'The HCI Methodology',
    intro_nl: 'Vier fasen, bewezen bij tech-bedrijven in Benelux en DACH. Van product-markt combinatie tot eerste klant.',
    intro_en: 'Four phases, proven with tech companies in Benelux and DACH. From product-market fit to first customer.',
    phases: [
      {
        num: '01',
        title: 'PMC',
        subtitle_nl: 'Product Market Combination',
        subtitle_en: 'Product Market Combination',
        desc_nl: 'Is uw product klaar voor de Europese markt? We valideren de product-markt fit, identificeren de juiste sectoren en bouwen de business case.',
        desc_en: 'Is your product ready for the European market? We validate product-market fit, identify the right sectors and build the business case.',
      },
      {
        num: '02',
        title: 'GTM',
        subtitle_nl: 'Go-to-Market Strategie',
        subtitle_en: 'Go-to-Market Strategy',
        desc_nl: 'Welk kanaal, welke partners, welke prijsstrategie. De GTM Calculator brengt uw investering en verwacht rendement in kaart.',
        desc_en: 'Which channel, which partners, which pricing strategy. The GTM Calculator maps your investment and expected return.',
      },
      {
        num: '03',
        title: 'Outreach',
        subtitle_nl: 'Data-driven Pipeline',
        subtitle_en: 'Data-driven Pipeline',
        desc_nl: 'Geen koude acquisitie. SignalMesh kwalificeert bezoekers automatisch. DealFlow beheert uw pipeline. Alleen warme leads komen door.',
        desc_en: 'No cold outreach. SignalMesh qualifies visitors automatically. DealFlow manages your pipeline. Only warm leads get through.',
      },
      {
        num: '04',
        title: 'Sales Execute',
        subtitle_nl: 'Van prospect naar klant',
        subtitle_en: 'From prospect to customer',
        desc_nl: 'De playbooks, de scripts, de objection handling. Bewezen in de praktijk bij Chunk Works, ElanWave en andere HCI klanten.',
        desc_en: 'The playbooks, the scripts, the objection handling. Proven in practice at Chunk Works, ElanWave and other HCI clients.',
      },
    ],
    partner_modules: {
      title_nl: 'Partner Enablement Platform',
      title_en: 'Partner Enablement Platform',
      modules: [
        { name: 'Convince', desc_nl: 'Business case voor partners', desc_en: 'Business case for partners' },
        { name: 'Onboard', desc_nl: 'Partner activatie en training', desc_en: 'Partner activation and training' },
        { name: 'Certify', desc_nl: 'Partner kwalificatie en certificering', desc_en: 'Partner qualification and certification' },
      ],
    },
  },
  // ── FOOTER ───────────────────────────────────────────────────────
  footer: {
    copyright: '© 2026 HES Consultancy International · hes-consultancy.nl',
    links: [
      { label_nl: 'Privacy', label_en: 'Privacy', href: '/privacy.html' },
      { label_nl: 'Voorwaarden', label_en: 'Terms', href: '/terms.html' },
    ],
  },
  // ── TOOLS ───────────────────────────────────────────────────────
  tools: {
    // Publiek toegankelijk (geen login)
    quickscan:   '/hci-quickscan.html',
    calculator:  '/calculator.html',
    insights:    '/insights.html',
    // Demo beschikbaar (gratis, beperkt)
    assessment:  '/hci-quickscan.html',
    // Achter softlock (Netlify Identity)
    modules:     '/hci-modules.html',
    pmc:         '/hci-pmc.html',
    gtm:         '/hci-gtm.html',
    outreach:    '/hci-outreach.html',
    sales:       '/hci-sales-execute.html',
    cmofmo:      '/hci-cmofmo.html',
    dealflow:    'https://dealflow.hes-consultancy-international.com',
    // Toegangssysteem
    access_system: 'netlify_identity',
    login_url:     '/modules',
    upgrade_url:   'https://calendly.com/mbhes1970/30min',
    upgrade_cta_nl: 'Plan een gesprek voor toegang →',
    upgrade_cta_en: 'Schedule a call for access →',
  },
  // ── INTELLIGENCE / SIGNALMESH ────────────────────────────────────
  intelligence: {
    debug:         false,
    slack_webhook_proxy: '/api/slack',
    pb_url:        'https://api.hes-consultancy-international.com',
    tier_thresholds: { cold: 0, warm: 20, hot: 45, tier1: 70 },
    scoring: {
      icp_param:    20,
      sector_param: 15,
      utm_email:    20,
      utm_linkedin: 15,
      utm_partner:  25,
      vid_present:  20,
      returning:    10,
      dwell_2min:    5,
      dwell_5min:   10,
      scroll_50:     3,
      scroll_80:     5,
    },
  },
};

// ── HELPERS ────────────────────────────────────────────────────────
window.getLang = function() {
  return localStorage.getItem('hci_lang') || 'nl';
};
window.t = function(nlText, enText) {
  return getLang() === 'en' ? enText : nlText;
};
window.tk = function(obj, key) {
  var lang = getLang();
  return obj[key + '_' + lang] || obj[key + '_nl'] || '';
};
